name: Setup TLPUI

on:
  push:
    branches: [ master ]
    tags:
     - '*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  appimage:
    name: "AppImage"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build AppImage
      run: |
        cd AppImage
        mkdir -p out
        ./pkg2appimage.sh

  save:
    name: "Saving AppImage"
    needs: appimage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Save AppImage
      run: |
        mv AppImage/out/*.AppImage ./tlpui.AppImage 
        git add tlpui.AppImage
        git commit -m "Adding testing AppImage"
        git push
